import { z } from 'zod'

const verifyTotpCodeSchema = z.object({
  code: z
    .string({
      invalid_type_error: 'Code must be a string.',
      required_error: 'Code is required',
    })
    .max(
      6,
      'Please provide the 6 digit code generated by your authenticator app.',
    )
    .min(
      6,
      'Please provide the 6 digit code generated by your authenticator app.',
    ),
})

export type VerifyTotpCodeSchemaType = z.infer<typeof verifyTotpCodeSchema>

export default verifyTotpCodeSchema
